version: '3.8'

# from env

services:
  n8n:
    build: .
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${n8n_password}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${host}
      - DB_POSTGRESDB_DATABASE=${database}
      - DB_POSTGRESDB_USER=${username}
      - DB_POSTGRESDB_PASSWORD=${password}
      - NODE_FUNCTION_ALLOW_EXTERNAL=pg
      - PORT=${port}
    ports:
      - "5555:5555"
  #   depends_on:
  #     - postgres

  # postgres:
  #   image: postgres:12
  #   environment:
  #     - POSTGRES_DB=n8n
  #     - POSTGRES_USER=n8n
  #     - POSTGRES_PASSWORD=n8n_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
